### ISSUE TITLE
Will not deploy

### ISSUE THREAD

**Issue by kd2eom** [Nordstrom/hello-retail-workshop#62]
Example 1 will not deploy in step 5 because there is nothing written in the accountId: field under coreStream in the private.yml file. The instructions do not explain what to put in this field before step 5, or even what coreStream is. Perhaps the instructions could be clarified?

**Comment by squareben1** [comment]
I am experiencing this same issue. Does anyone have the answer?

**Comment by gwsii** [comment]
The workshop was run so that students would create an event consumer from a core stream. The core stream is created by those who run the workshop, so it's in a different account. Suppose there is no reason that a single account could be used, but we're unlikely to take the time to update the instructions for that case in the near future.
